version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mydb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"   # Exponer el puerto 3308 al puerto 3306 interno de MySQL
    volumes:
      - ./sql-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  app:
    build: .
    container_name: api-app
    ports:
      - "3000:3000"   # Exponer el puerto 3000
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
      DB_PORT: 3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
